--- #YAML:1.0
name:                Mail-IMAPClient
version:             3.17
abstract:            IMAP4 client library
license:             ~
author:              
    - Phil Lobbes <phil@zimbra.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    Errno:                         0
    Fcntl:                         0
    File::Temp:                    0
    IO::File:                      0
    IO::Select:                    0
    IO::Socket:                    0
    IO::Socket::INET:              1.26
    List::Util:                    0
    MIME::Base64:                  0
    Parse::RecDescent:             1.94
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
