=head1 NAME

Mail::IMAPClient::BodyStructure::Parse - used internally by Mail::IMAPClient::BodyStructure

=head1 INHERITANCE

=head1 SYNOPSIS

This module is used internally by L<Mail::IMAPClient::BodyStructure>
and is not meant to be used or called directly from applications. So
don't do that.

=head1 DESCRIPTION

This module is used internally by L<Mail::IMAPClient::BodyStructure>
and is generated using L<Parse::RecDescent>. It is not meant to be used
directly by other scripts nor is there much point in debugging it.

=head1 SEE ALSO

This module is part of Mail-IMAPClient distribution version 3.07,
built on April 28, 2008.

=head1 LICENSE

Copyrights 2008. For other contributors see Changes.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
See F<http://www.perl.com/perl/misc/Artistic.html>

